language: go
before_install:
- go get -u github.com/golang/lint/golint
- go get -u github.com/mattn/goveralls
- gometalinter --install --update
script:
- make
- go vet
- gometalinter --vendor
- go test -v -covermode=count -coverprofile=profile.cov
- goveralls -coverprofile=profile.cov -service=travis-ci
after_script:
- go tool cover -func=profile.cov
go:
- '1.6'
- '1.7'
- tip
matrix:
  fast_finish: true
notifications:
  slack:
    secure: IyeUhBqef86BABECXtQMIT45ofTLacDRAKFbx1o13cR4rb5Xg+uWDbGrzMfykRHFzbo5MpKw0JahIBWNb7vAKYatccLxXOXMBIMasStmOnQg7lLASlrVAIzWhJhuFhQnGi7L39iPj3joCq8lpVKMmM5A3gKW90L061ovZVDdxB1ImTbQls0n/suG5zZg8To1WfUJQueG8iMQeuV9VNxOi/lKgJRkW7Omenh2RogA8sdlItmm4sxIZpy5qsSWOB75KQlJ8RLvHIwl1xAMgxWZSBH/xiELHSQPyc0/DrOWgRAaYblWKoUg/N2HTWn5iua6KJ0kiV+53nY6BGGk6yMtiYmyxuh8h+lm7czll1PuesD6CW8YDriJpxywRWNxVf393tekqf0smvYWttyAQmD908di9kA+Evzr/UtbTKlewX3ntY+SftPnQu9Wn1oFsT1Qib6iLQYicrK/UcYNgw4Q5ofb6rvpAsFuKpg5g8sv9wrnzP2sSMi2NgfKOrFczHm4va+vLsJZtS0xoSV928cXX0LLwB3jVI3QhusSh0ZxYgbAfJ+N8wGxbSWn17hUZBVz5pnmGssXkcVeWEOMhp2Wt7RilQ9/PwIXz6XbR23+HlTwXOZ+lff/oFHbfjRJHnLuAXV+R8GZ+1zzaSd4bFNnLVLSJ9YhMavCrftAIktVshY=
